STEAMID_DISSEMINATE = "STEAM_0:0:17359435";

MALE = 1;
FEMALE = 2;

CHARCREATE_SELECT = 1;
CHARCREATE_DELETE = 2;
CHARCREATE_SELECTCLASS = 3;
CHARCREATE_SURVIVOR = 4;
CHARCREATE_HECU = 5;
CHARCREATE_INFECTED = 6;
CHARCREATE_SPECIALINFECTED = 7;

SONG_LIGHT = 1;
SONG_MEDIUM = 2;
SONG_HEAVY = 3;

IRON_HOLSTERED = 0;
IRON_HOLSTERED2IDLE = 1;
IRON_IDLE = 2;
IRON_IDLE2AIM = 3;
IRON_AIM = 4;

TEAM_SURVIVOR = 1;

CB_ALL = 1;
CB_IC = 2;
CB_OOC = 3;

COLOR_ERROR = Color( 255, 0, 0, 255 );
COLOR_NOTIFY = Color( 255, 200, 75, 255 );

PLAYERCLASS_SURVIVOR = 1;
PLAYERCLASS_MILITARY = 2;
PLAYERCLASS_INFECTED = 3;
PLAYERCLASS_SPECIALINFECTED = 4;

SI_JUMPER = 1;